name: Bug Report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
        
        Before filling out this form, please:
        - Search for [existing issues](https://github.com/Chevey339/kelivo/issues) to avoid duplicates
        - Make sure you're using the latest version of the application
  
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Screenshots or Video
      description: If applicable, add screenshots or a screen recording to help explain your problem.
      value: |
        <details open>
        <summary>Screenshots / Video demonstration</summary>
        [Upload media here]
        </details>
  
  - type: textarea
    attributes:
      label: Environment
      description: Please provide information about your environment.
      value: |
        - Device: [e.g. iPhone 14]
        - OS: [e.g. iOS 17, Windows 11]
        - App Version: [e.g. v1.0.8(5)]
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here, such as error logs 
        from the browser console or any other relevant information.
      value: |
        <details open><summary>Additional information</summary>
        ```
        [Paste any logs or additional context here]
        ```
        </details>